/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yyf_jnidemo_PropertyUtils */

#ifndef _Included_com_yyf_jnidemo_PropertyUtils
#define _Included_com_yyf_jnidemo_PropertyUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yyf_jnidemo_PropertyUtils
 * Method:    getProperty
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_yyf_jnidemo_PropertyUtils_getProperty
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_yyf_jnidemo_PropertyUtils
 * Method:    setProperty
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_yyf_jnidemo_PropertyUtils_setProperty
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
